###################################################
#     Base Brewfile for all departments           #
###################################################

tap 'homebrew/cask'
tap 'homebrew/bundle'
tap 'homebrew/core'

### OSX Terminal stuff that will make your life easier
brew 'bash'

### System tools
cask '1password'
cask 'appcleaner'

# let you mount windows drives and write on it
cask 'macfuse'

### Internet stuff
cask 'google-chrome'
cask 'responsively'

### Collaboration & communication
cask 'dropbox'
cask 'teamviewer'

### Microsoft
cask 'microsoft-remote-desktop'
cask 'microsoft-office'
cask 'microsoft-teams'

### Multimedia & Tools
cask 'spotify'
cask 'airtame'
